repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-illegal-windows-names
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: name-tests-test
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.7
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format
    - id: ruff-check
- repo: local
  hooks:
    - id: ty-check
      name: ty-check
      entry: uvx ty check
      language: python
      types: [python]
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
  - id: detect-secrets
- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.11.0
  hooks:
  - id: shellcheck
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    additional_dependencies:
      - tomli
