[build-system]
requires = ["setuptools>=43.0.0"]
build-backend = "setuptools.build_meta"

[tool.mypy]
implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
allow_redefinition = true
local_partial_types = true
strict_equality = true
install_types = true

[tool.ruff]
select = ["ALL"]
ignore = [
    # Allow public structures without docstrings
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    # Allow implicit namespace packages
    "INP",
    # Allow print statements
    "T20",
]

[tool.ruff.flake8-annotations]
allow-star-arg-any = true
ignore-fully-untyped = true

[tool.ruff.pydocstyle]
convention = "google"
